version: '3'
services:
    postgresdb:
        image: postgres:latest
        restart: unless-stopped
        container_name: postgres-container
        ports:
            - "0.0.0.0:5432:5432"
        environment:
            POSTGRES_DB: project
            POSTGRES_PASSWORD: admin
        volumes:
            - ./postgres-data:/var/lib/mysql:rw
            - ./postgres-scripts/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
